### ISSUE TITLE
calling ResultsTable before RunGscreend does not throw an error

### ISSUE THREAD

**Issue by jan-glx** [imkeller/gscreend#2]
Calling `gscreend::ResultsTable` with a `PoolScreenExp` object which was never returned by a call to `gscreend::RunGscreend` ("on which Gscreend was never run") returns a strange data.table instead of throwing an error.
```R
gscreend::ResultsTable(pse) # where `pse` is e.g. the same named object from the example
# [1] pval
# <0 rows> (or 0-length row.names)
```

**Comment by imkeller** [comment]
The functions ResultsTable() and plotModelParameters() now raise an error when you try to run them on an object that has not been analysed.
