### ISSUE TITLE
gene that is both depleted and enriched?

### ISSUE THREAD

**Issue by rafaelgalupa** [imkeller/gscreend#4]
Hi! I've been running gscreend on the results of a screen and I've just come across something unexpected. There's a gene (Dusp9) that appears significant when running gscreend direction "negative", as well as direction "positive". The log fold change value is negative... not sure this is supposed to be happening? Thank you. I'm attaching my code and a table with my raw counts.
[Code_gscreend_rgalupa.txt](https://github.com/imkeller/gscreend/files/12188550/Code_gscreend_rgalupa.txt)
[Galaxy434_raw_sgRNA_Counts.tabular.zip](https://github.com/imkeller/gscreend/files/12188553/Galaxy434_raw_sgRNA_Counts.tabular.zip)

**Comment by imkeller** [comment]
Hi @rafaelgalupa ,
it can be, that a gene has both positive and negative enrichment. Biologically speaking, the sgRNAs may target different regions of the gene, leading to sgRNA specific effects. In your case, my impression is that the first replicate (ED121) has a few sgRNA outliers with very high counts. This affects the count normalization.

**Comment by rafaelgalupa** [comment]
Hi Katharina! Ah yes, that makes sense. Thank you very much for looking into this!
